version: "3.9"
services:
  sd:
    build: .
    ports:
      - "3000:7860"
    volumes:
#      - ./models:/SD/stable-diffusion-webui/models/
#      - ./repositories:/SD/stable-diffusion-webui/repositories/
      - ./stable-diffusion-webui:/SD/stable-diffusion-webui/
    devices:
      - '/dev/kfd:/dev/kfd'
      - '/dev/dri:/dev/dri'
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
